In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
healthData = pd.read_csv('Health.csv')
print(healthData)

  Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     Asian        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes


In [3]:
X = healthData.iloc[:,0:3].values
y = healthData.iloc[:,3].values

In [4]:
X

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['Asian', 175.0, 80.0],
       ['White', 180.0, 88.0],
       ['Asian', 178.0, nan],
       ['Asian', 172.0, 72.0],
       ['African', 178.0, 75.0],
       ['White', nan, 89.0],
       ['African', 186.0, 90.0]], dtype=object)

In [5]:
y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [6]:
from sklearn.preprocessing import Imputer
missingValueImputer = Imputer(missing_values = 'NaN', strategy = 'mean',
                             axis = 0)
missingValueImputer = missingValueImputer.fit(X[:,1:3]) # Sets the columns
X[:,1:3] = missingValueImputer.transform(X[:,1:3]) #Update the columns
print(X)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['Asian' 175.0 80.0]
 ['White' 180.0 88.0]
 ['Asian' 178.0 85.25]
 ['Asian' 172.0 72.0]
 ['African' 178.0 75.0]
 ['White' 180.0 89.0]
 ['African' 186.0 90.0]]


In [7]:
from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X[:,0] = X_labelencoder.fit_transform(X[:,0])
print(X)
y_labelencoder = LabelEncoder()
y = y_labelencoder.fit_transform(y)
print(y)


[[2 186.0 90.0]
 [0 185.0 98.0]
 [1 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 85.25]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 180.0 89.0]
 [0 186.0 90.0]]
[1 0 0 1 0 1 0 1 1]


In [8]:
from sklearn.preprocessing import OneHotEncoder
x_onehotencoder = OneHotEncoder(categorical_features = [0])
X = x_onehotencoder.fit_transform(X).toarray()
print(X)

[[   0.      0.      1.    186.     90.  ]
 [   1.      0.      0.    185.     98.  ]
 [   0.      1.      0.    175.     80.  ]
 [   0.      0.      1.    180.     88.  ]
 [   0.      1.      0.    178.     85.25]
 [   0.      1.      0.    172.     72.  ]
 [   1.      0.      0.    178.     75.  ]
 [   0.      0.      1.    180.     89.  ]
 [   1.      0.      0.    186.     90.  ]]


In [9]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                   random_state = 0)
print(X_test, y_test)

[[   0.    0.    1.  180.   89.]
 [   0.    1.    0.  175.   80.]] [1 0]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
from sklearn.preprocessing import StandardScaler
independent_scaler = StandardScaler()
X_train = independent_scaler.fit_transform(X_train)
X_test = independent_scaler.transform(X_test)
print(X_train)

[[ 1.15470054 -0.63245553 -0.63245553  0.88159065  1.48988518]
 [-0.8660254   1.58113883 -0.63245553 -0.55834074 -0.02546812]
 [ 1.15470054 -0.63245553 -0.63245553  1.08729513  0.53907526]
 [ 1.15470054 -0.63245553 -0.63245553 -0.55834074 -1.24369333]
 [-0.8660254  -0.63245553  1.58113883 -0.14693177  0.30137279]
 [-0.8660254  -0.63245553  1.58113883  1.08729513  0.53907526]
 [-0.8660254   1.58113883 -0.63245553 -1.79256765 -1.60024704]]


In [11]:
from sklearn.preprocessing import StandardScaler
independent_scaler = StandardScaler()
X_train = independent_scaler.fit_transform(X_train)
X_test = independent_scaler.transform(X_test)
print(X_train)

[[ 1.15470054 -0.63245553 -0.63245553  0.88159065  1.48988518]
 [-0.8660254   1.58113883 -0.63245553 -0.55834074 -0.02546812]
 [ 1.15470054 -0.63245553 -0.63245553  1.08729513  0.53907526]
 [ 1.15470054 -0.63245553 -0.63245553 -0.55834074 -1.24369333]
 [-0.8660254  -0.63245553  1.58113883 -0.14693177  0.30137279]
 [-0.8660254  -0.63245553  1.58113883  1.08729513  0.53907526]
 [-0.8660254   1.58113883 -0.63245553 -1.79256765 -1.60024704]]
